/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { OrderService } from "../order.service";
import { OrderCreateInput } from "./OrderCreateInput";
import { Order } from "./Order";
import { OrderFindManyArgs } from "./OrderFindManyArgs";
import { OrderWhereUniqueInput } from "./OrderWhereUniqueInput";
import { OrderUpdateInput } from "./OrderUpdateInput";
import { DeliveryContractFindManyArgs } from "../../deliveryContract/base/DeliveryContractFindManyArgs";
import { DeliveryContract } from "../../deliveryContract/base/DeliveryContract";
import { DeliveryContractWhereUniqueInput } from "../../deliveryContract/base/DeliveryContractWhereUniqueInput";

export class OrderControllerBase {
  constructor(protected readonly service: OrderService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Order })
  async createOrder(@common.Body() data: OrderCreateInput): Promise<Order> {
    return await this.service.createOrder({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        pointA: true,
        weight: true,
        size: true,
        remuneration: true,
        status: true,
        description: true,
        pointB: true,
        deliveryTime: true,
        sender: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Order] })
  @ApiNestedQuery(OrderFindManyArgs)
  async orders(@common.Req() request: Request): Promise<Order[]> {
    const args = plainToClass(OrderFindManyArgs, request.query);
    return this.service.orders({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        pointA: true,
        weight: true,
        size: true,
        remuneration: true,
        status: true,
        description: true,
        pointB: true,
        deliveryTime: true,
        sender: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Order })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async order(
    @common.Param() params: OrderWhereUniqueInput
  ): Promise<Order | null> {
    const result = await this.service.order({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        pointA: true,
        weight: true,
        size: true,
        remuneration: true,
        status: true,
        description: true,
        pointB: true,
        deliveryTime: true,
        sender: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Order })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOrder(
    @common.Param() params: OrderWhereUniqueInput,
    @common.Body() data: OrderUpdateInput
  ): Promise<Order | null> {
    try {
      return await this.service.updateOrder({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          pointA: true,
          weight: true,
          size: true,
          remuneration: true,
          status: true,
          description: true,
          pointB: true,
          deliveryTime: true,
          sender: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Order })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOrder(
    @common.Param() params: OrderWhereUniqueInput
  ): Promise<Order | null> {
    try {
      return await this.service.deleteOrder({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          pointA: true,
          weight: true,
          size: true,
          remuneration: true,
          status: true,
          description: true,
          pointB: true,
          deliveryTime: true,
          sender: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/deliveryContracts")
  @ApiNestedQuery(DeliveryContractFindManyArgs)
  async findDeliveryContracts(
    @common.Req() request: Request,
    @common.Param() params: OrderWhereUniqueInput
  ): Promise<DeliveryContract[]> {
    const query = plainToClass(DeliveryContractFindManyArgs, request.query);
    const results = await this.service.findDeliveryContracts(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        terms: true,
        price: true,
        status: true,

        order: {
          select: {
            id: true,
          },
        },

        performerProfile: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/deliveryContracts")
  async connectDeliveryContracts(
    @common.Param() params: OrderWhereUniqueInput,
    @common.Body() body: DeliveryContractWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      deliveryContracts: {
        connect: body,
      },
    };
    await this.service.updateOrder({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/deliveryContracts")
  async updateDeliveryContracts(
    @common.Param() params: OrderWhereUniqueInput,
    @common.Body() body: DeliveryContractWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      deliveryContracts: {
        set: body,
      },
    };
    await this.service.updateOrder({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/deliveryContracts")
  async disconnectDeliveryContracts(
    @common.Param() params: OrderWhereUniqueInput,
    @common.Body() body: DeliveryContractWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      deliveryContracts: {
        disconnect: body,
      },
    };
    await this.service.updateOrder({
      where: params,
      data,
      select: { id: true },
    });
  }
}
